### ISSUE TITLE
CAnt get it to start

### ISSUE THREAD

**Issue by jstarstech** [JincorTech/b2but-frontend-ico-dashboard#18]
jstars@server:~/nodejs/b2but-frontend-ico-dashboard$ npm run eslint
npm ERR! Linux 4.4.0-122-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "eslint"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2

npm ERR! missing script: eslint
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jstars/nodejs/b2but-frontend-ico-dashboard/npm-debug.log

**Comment by hlogeon** [comment]
You don't . need to run eslint. You can get the list of all script available in package.js
https://github.com/JincorTech/b2but-frontend-ico-dashboard/blob/master/package.json#L8

The actual problem is outdated documentation.
You can run `npm start` to get it running
